# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/agi/Documents/_TUM/group_80

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/agi/Documents/_TUM/group_80

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/agi/Documents/_TUM/group_80/CMakeFiles /mnt/c/Users/agi/Documents/_TUM/group_80//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/agi/Documents/_TUM/group_80/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named group_80

# Build rule for target.
group_80: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 group_80
.PHONY : group_80

# fast build rule for target.
group_80/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/build
.PHONY : group_80/fast

src/FileReader.o: src/FileReader.cpp.o
.PHONY : src/FileReader.o

# target to build an object file
src/FileReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/FileReader.cpp.o
.PHONY : src/FileReader.cpp.o

src/FileReader.i: src/FileReader.cpp.i
.PHONY : src/FileReader.i

# target to preprocess a source file
src/FileReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/FileReader.cpp.i
.PHONY : src/FileReader.cpp.i

src/FileReader.s: src/FileReader.cpp.s
.PHONY : src/FileReader.s

# target to generate assembly for a file
src/FileReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/FileReader.cpp.s
.PHONY : src/FileReader.cpp.s

src/InputWallet.o: src/InputWallet.cpp.o
.PHONY : src/InputWallet.o

# target to build an object file
src/InputWallet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/InputWallet.cpp.o
.PHONY : src/InputWallet.cpp.o

src/InputWallet.i: src/InputWallet.cpp.i
.PHONY : src/InputWallet.i

# target to preprocess a source file
src/InputWallet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/InputWallet.cpp.i
.PHONY : src/InputWallet.cpp.i

src/InputWallet.s: src/InputWallet.cpp.s
.PHONY : src/InputWallet.s

# target to generate assembly for a file
src/InputWallet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/InputWallet.cpp.s
.PHONY : src/InputWallet.cpp.s

src/StdInReader.o: src/StdInReader.cpp.o
.PHONY : src/StdInReader.o

# target to build an object file
src/StdInReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/StdInReader.cpp.o
.PHONY : src/StdInReader.cpp.o

src/StdInReader.i: src/StdInReader.cpp.i
.PHONY : src/StdInReader.i

# target to preprocess a source file
src/StdInReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/StdInReader.cpp.i
.PHONY : src/StdInReader.cpp.i

src/StdInReader.s: src/StdInReader.cpp.s
.PHONY : src/StdInReader.s

# target to generate assembly for a file
src/StdInReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/StdInReader.cpp.s
.PHONY : src/StdInReader.cpp.s

src/Stock.o: src/Stock.cpp.o
.PHONY : src/Stock.o

# target to build an object file
src/Stock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Stock.cpp.o
.PHONY : src/Stock.cpp.o

src/Stock.i: src/Stock.cpp.i
.PHONY : src/Stock.i

# target to preprocess a source file
src/Stock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Stock.cpp.i
.PHONY : src/Stock.cpp.i

src/Stock.s: src/Stock.cpp.s
.PHONY : src/Stock.s

# target to generate assembly for a file
src/Stock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Stock.cpp.s
.PHONY : src/Stock.cpp.s

src/Strategy.o: src/Strategy.cpp.o
.PHONY : src/Strategy.o

# target to build an object file
src/Strategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Strategy.cpp.o
.PHONY : src/Strategy.cpp.o

src/Strategy.i: src/Strategy.cpp.i
.PHONY : src/Strategy.i

# target to preprocess a source file
src/Strategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Strategy.cpp.i
.PHONY : src/Strategy.cpp.i

src/Strategy.s: src/Strategy.cpp.s
.PHONY : src/Strategy.s

# target to generate assembly for a file
src/Strategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Strategy.cpp.s
.PHONY : src/Strategy.cpp.s

src/Wallet.o: src/Wallet.cpp.o
.PHONY : src/Wallet.o

# target to build an object file
src/Wallet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Wallet.cpp.o
.PHONY : src/Wallet.cpp.o

src/Wallet.i: src/Wallet.cpp.i
.PHONY : src/Wallet.i

# target to preprocess a source file
src/Wallet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Wallet.cpp.i
.PHONY : src/Wallet.cpp.i

src/Wallet.s: src/Wallet.cpp.s
.PHONY : src/Wallet.s

# target to generate assembly for a file
src/Wallet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/Wallet.cpp.s
.PHONY : src/Wallet.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/market_simulator.o: src/market_simulator.cpp.o
.PHONY : src/market_simulator.o

# target to build an object file
src/market_simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/market_simulator.cpp.o
.PHONY : src/market_simulator.cpp.o

src/market_simulator.i: src/market_simulator.cpp.i
.PHONY : src/market_simulator.i

# target to preprocess a source file
src/market_simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/market_simulator.cpp.i
.PHONY : src/market_simulator.cpp.i

src/market_simulator.s: src/market_simulator.cpp.s
.PHONY : src/market_simulator.s

# target to generate assembly for a file
src/market_simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/group_80.dir/build.make CMakeFiles/group_80.dir/src/market_simulator.cpp.s
.PHONY : src/market_simulator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... group_80"
	@echo "... src/FileReader.o"
	@echo "... src/FileReader.i"
	@echo "... src/FileReader.s"
	@echo "... src/InputWallet.o"
	@echo "... src/InputWallet.i"
	@echo "... src/InputWallet.s"
	@echo "... src/StdInReader.o"
	@echo "... src/StdInReader.i"
	@echo "... src/StdInReader.s"
	@echo "... src/Stock.o"
	@echo "... src/Stock.i"
	@echo "... src/Stock.s"
	@echo "... src/Strategy.o"
	@echo "... src/Strategy.i"
	@echo "... src/Strategy.s"
	@echo "... src/Wallet.o"
	@echo "... src/Wallet.i"
	@echo "... src/Wallet.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/market_simulator.o"
	@echo "... src/market_simulator.i"
	@echo "... src/market_simulator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

